### ISSUE TITLE
Issue with .qmd render

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw01-ShakirAhmed#1]
Hi Shakir, 

The autograder ran into this issue when trying to render your .qmd file:

```
Quitting from lines 340-344 [unnamed-chunk-4] (hw-01.qmd)
Error in `setwd()`:
! cannot change working directory
Backtrace:
 1. base::setwd("/cloud/project/data")
```

The issue is because the working directory is not standardized. I suggest using the `here` package: 
`pacman::p_load("tidyverse", "here")`

Then where the directory is set: 
`troops <- readRDS(here("data", "napoleon.rds"))`

This should resolve the issue. Push the changes then the autograder will check again.

**Comment by Shakir0585** [comment]
Hi Greg,

Fixed issues and ensured the job ran successfully. Green tick on repo to confirm! 

Thanks for the help!
