### ISSUE TITLE
Homework 1 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw01-ShakirAhmed#2]
Dear [Shakir0585] -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

---

### Exercise 1: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [No need to include the question prompts, but if it helps you then it helps me!]

### Exercise 2: `[20 / 20 points]`

a. `[8 / 8 points]`

  - Histogram: `[3 / 3]`
  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [Insert feedback here.]

b. `[5 / 5 points]`

  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [The Men and Women graphs needed to be faceted more info: http://www.sthda.com/english/wiki/ggplot2-facet-split-a-plot-into-a-matrix-of-panels
  - The captions is competing with the x-axis label for space. Maybe place the caption left aligned, or include a new line in the string example: ... caption= "\nNYC Marathon dataset in OpenIntro package" ...]

- [x] Resolved

c. `[2 / 2 points]`

  - Feedback: [Your x-axis says year when it should be time, unless the axis labels are wrong? your y axis says time when it's the division of genders. Also you could have had men/women as just the legend]
- [x] Resolved

d. `[5 / 5 points]`

  - Time series plot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: [Insert feedback here.]

### Exercise 3: `[20 / 20 points]`

a. `[2 / 2]`
  - Feedback: [Insert feedback here.]

b. `[2 / 2]`
  - Feedback: [Insert feedback here.]

c. `[16 / 16]` (2 points each)
  - Feedback: [Here you might want to use the grid.arrange(), to align the graphs. Some info: https://cran.r-project.org/web/packages/gridExtra/vignettes/arrangeGrob.html ; https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html]

-[x] Resolved

Additional feedback: Good work using the `grid.arrange()`, however your `heights = c(10,10)` argument should be heights = c(5,5) since the plots are only in one row. You could also remove the widths and heights altogether and it would be okay. 
  
### Exercise 4: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [In your discussion you need an interpretation of the findings of how rental prices vary over time and neighborhoods in San Francisco."]
- [x] Resolved

### Exercise 5: `[20 / 20 points]`

Feedback: [Insert feedback here.]

### Overall: `[20/ 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by Shakir0585** [comment]
Hi Greg,
Thank you for your suggestions! Will implement it in a following commit sometime soon. 

One small issue- For Exercise 2, the total calculation is displaying "15/20" instead of "17/20" which is the overall score. Will this impact the final marks?

Also one questions- will the marks and grading be updated post this? I do realize that overall, i have received a 20/20, but i would like to improve it based on  each section as well.

**Comment by Gchism94** [comment]
The Exercise 2 grade is now correct.

**Comment by Shakir0585** [comment]
Hi Greg,

Made the following changes:
1. Exercise 2.b- 
-Corrected cation spacing for x-axis labels. 
-Removed legend to make the boxplot appear more spacious. I tried faceting, but the result is showing comparably the same as earlier.

2. Exercise 2.c-
-Corrected x and y axis labeling.
-Included men/women as just the legend.
 
3. Exercise 3.c- 
- Used the grid.allign() function to align the graphs next to each other, as per Github repo figures.

4. Exercise 4-
-Discussion of how the rental prices varied across time is defined below the heatmap. It shows the different gradient of color, which is how the trends is shown. I have included the observations for histogram as well.

Please let me know in case i have missed anything, or can make something better.

**Comment by Gchism94** [comment]
Good work resolving the issues, you now received full credit.

**Comment by Shakir0585** [comment]
Thank you so much!
